spring:
  application:
    name: forest
  datasource:
    url: jdbc:oracle:thin:@192.168.20.203:1521:xe
    username: FOREST
    password: FOREST
    driver-class-name: oracle.jdbc.driver.OracleDriver
  mvc:
    static-path-pattern: /uploads/**
  web:
    resources:
      static-locations: file:uploads/
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 80

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    jdbc-type-for-null: VARCHAR
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.dev.forest.quiz.model.dto, com.dev.forest.wrong.model.dto, com.dev.forest.member.model.dto, com.dev.forest.token.model.dto, com.dev.forest.theory.model.dto, com.dev.forest.progress.model.dto, com.dev.forest.ranking.model.dto

logging:
  level:
    org.apache.ibatis: DEBUG
    java.sql: DEBUG
    jdbc.sqlonly: DEBUG
    jdbc.resultset: DEBUG
    jdbc.audit: DEBUG

jwt:
  secret: ixT+57RqcN/H4zaeGMfDaiw32qxGOfO3MjY+XITjgNI=